3648 - inseridas as datas de inicio e fim da vigencia
Spincare-Pulsati/spincare-frontend pull request #1419
Opened 2023-01-11 14:38 UTC by SantosAnaCarolina

2023-01-11 18:31 UTC, bologninidiego requested changes

2023-01-11 18:31 UTC, bologninidiego commented on src/app/main/cadastro/profissional/components/imagem-list/imagem-list.component.ts
>        localStorage.setItem('currentTabPaciente', JSON.stringify(6));
Não seria a tab do profissional?

2023-01-11 18:31 UTC, bologninidiego commented on src/app/main/cadastro/profissional/components/imagem-list/imagem-list.component.ts
> +      && event.cellIndex !== 5
Não seria mais interessante criar uma coluna  com um botão de "Ver detalhes" e só rotear de fato quando clicar no botão? Isso previne essa lógica de cell Index feiosa 😃

2023-01-12 15:02 UTC, bologninidiego requested changes

2023-01-12 15:02 UTC, bologninidiego commented on src/app/main/cadastro/profissional/components/imagem-list/imagem-list.component.ts
> +    localStorage.setItem('currentTabPaciente', JSON.stringify(6));
Ainda está currentTabPaciente 😢

2023-01-12 18:51 UTC, SantosAnaCarolina commented on src/app/main/cadastro/profissional/components/imagem-list/imagem-list.component.ts
> +    localStorage.setItem('currentTabPaciente', JSON.stringify(6));
Foi mal, achei que estava falando de outa coisa

2023-01-12 19:36 UTC, bologninidiego approved these changes
👍

2023-01-13 11:08 UTC, merged