9695 - inseridos campos de autorizacao e senha nas contas nas listas …
Spincare-Pulsati/spincare-frontend pull request #1427
Opened 2023-01-12 18:36 UTC by SantosAnaCarolina

…e filtros

2023-01-12 19:38 UTC, bologninidiego requested changes

2023-01-12 19:38 UTC, bologninidiego commented on src/app/main/financeiro/conta/conta.component.html
> +                <div fxLayout="row" fxLayout.xs="column" fxLayoutAlign="start" fxLayoutGap="15px"
Seria importante frizar na div com título que tratam-se de filtros, já que foi retirado o "Filtrar por" dos inputs.

2023-01-12 19:38 UTC, bologninidiego commented on src/app/main/financeiro/lote-conta/components/lote-conta-contas-list/lote-conta-contas-list.component.html
> +            <mat-form-field class="m-4" fxFlex="30" [floatLabel]="true">
Porque m-4 nos campos?

2023-01-13 17:25 UTC, SantosAnaCarolina commented on src/app/main/financeiro/conta/conta.component.html
> +                <div fxLayout="row" fxLayout.xs="column" fxLayoutAlign="start" fxLayoutGap="15px"
Feito

2023-01-13 17:29 UTC, SantosAnaCarolina commented on src/app/main/financeiro/lote-conta/components/lote-conta-contas-list/lote-conta-contas-list.component.html
> +            <mat-form-field class="m-4" fxFlex="30" [floatLabel]="true">
Corrigido

2023-01-16 12:59 UTC, merged