#8258 - Implementando impressao na nova tela de conciliacoes
Spincare-Pulsati/spincare-frontend pull request #1429
Opened 2023-01-13 11:29 UTC by bortolattolucas

2023-01-13 21:05 UTC, bologninidiego requested changes

2023-01-13 21:05 UTC, bologninidiego commented on src/app/main/financeiro/conciliacao-conta-bancaria/conciliacao-conta-bancaria.component.html
> +                        [disabled]="!form.get('idConta').value || form.get('idConta').value == ''
Porque .value== '' ?

2023-01-13 21:42 UTC, bortolattolucas commented on src/app/main/financeiro/conciliacao-conta-bancaria/conciliacao-conta-bancaria.component.html
> +                        [disabled]="!form.get('idConta').value || form.get('idConta').value == ''
Removido

2023-01-16 12:44 UTC, bologninidiego approved these changes
👍

2023-01-16 12:49 UTC, merged