Ticket 6613
Spincare-Pulsati/spincare-frontend pull request #1437
Opened 2023-01-16 17:25 UTC by Firekepr

2023-01-16 19:02 UTC, bologninidiego requested changes

2023-01-16 19:02 UTC, bologninidiego commented on src/app/service/utils/utils.service.ts
> +    console.log(window.innerHeight, window.innerWidth);
Chegou a testar com tablet pra ver?

2023-01-16 19:02 UTC, bologninidiego commented on src/app/main/paciente/painel-paciente/painel-paciente.component.html
> +						<mat-form-field fxFlex="30" class="mt-12 mb-6">
Todos esses mt-12 mb-6 não são resolvidos com layoutGap?

2023-01-16 19:02 UTC, bologninidiego commented on src/app/main/paciente/painel-paciente/components/painel-paciente-list/painel-paciente-list.component.html
> +                    <div *ngIf="row[col.id] === 'rep'" [ngStyle]="{'padding-left': 22 + 'px' }">
Essa linha:
[ngStyle]="{'padding-left': 22 + 'px' }"
Não fica estranho quando aplicada em mobile?

2023-01-16 19:11 UTC, Firekepr commented on src/app/main/paciente/painel-paciente/painel-paciente.component.html
> +						<mat-form-field fxFlex="30" class="mt-12 mb-6">
Na realidade esse mt-12 e mb-6 era pra mim ter sido removido, acabei esquecendo por falta de atenção, mas resolvido, classes removidas.

2023-01-16 19:31 UTC, Firekepr commented on src/app/main/paciente/painel-paciente/components/painel-paciente-list/painel-paciente-list.component.html
> +                    <div *ngIf="row[col.id] === 'rep'" [ngStyle]="{'padding-left': 22 + 'px' }">
Esse padding não fica estranho pois está dentro da lista do painel do paciente, e não tem muito o que fazer sobre, mas foi ajustado a descrição de cada ícone para que fique mais legível.

2023-01-16 19:32 UTC, Firekepr commented on src/app/service/utils/utils.service.ts
> +    console.log(window.innerHeight, window.innerWidth);
Testado em table e celular com base nos modelos de Iphone SE / XR e Ipad mini

2023-01-17 01:18 UTC, bologninidiego approved these changes
👍

2023-01-17 01:18 UTC, merged