[3658] parte1 - incluído o campo Status do processo seletivo
Spincare-Pulsati/spincare-frontend pull request #1439
Opened 2023-01-16 18:59 UTC by SantosAnaCarolina

2023-01-16 19:04 UTC, bologninidiego requested changes

2023-01-16 19:04 UTC, bologninidiego commented on src/app/main/cadastro/profissional/components/profissional-form/profissional-form.component.ts
> +      this.nrStatusOriginal = data.selective_process_id;
nrStatusOriginal não é um nome sugestivo..

2023-01-16 19:04 UTC, bologninidiego commented on src/app/main/cadastro/profissional/components/profissional-form/profissional-form.component.html
> +                                <mat-option [value]="1"> Em processo de seleção </mat-option>
Essa lista deve vir do banco, certo?

2023-01-17 13:35 UTC, SantosAnaCarolina commented on src/app/main/cadastro/profissional/components/profissional-form/profissional-form.component.ts
> +      this.nrStatusOriginal = data.selective_process_id;
Alterei para firstSelectiveProcessNumberSaved

2023-01-17 13:35 UTC, SantosAnaCarolina commented on src/app/main/cadastro/profissional/components/profissional-form/profissional-form.component.html
> +                                <mat-option [value]="1"> Em processo de seleção </mat-option>
Certo. Corrigido.

2023-01-17 19:23 UTC, merged